services:
  backend:
    build: ./backend
    container_name: borde_backend
    ports:
      - "8000:8000"
    volumes:
      - ./mitm/data:/data
      - ./output:/output
    environment:
      - APP_ENV=dev
    networks:
      - borde_net

  frontend:
    build: ./frontend
    container_name: borde_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    depends_on:
      - backend
    networks:
      - borde_net

  mitm:
    build: ./mitm
    container_name: borde_mitm
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./mitm/data:/data
      - ./mitm/input:/input
    networks:
      - borde_net
    command: /bin/sh -c "mkdir -p /data && mitmweb --listen-host 0.0.0.0 --listen-port 8080 --web-host 0.0.0.0 --web-port 8081 --set confdir=/data -w /data/flows.mitm"

  mitm-converter:
    build: ./mitm
    container_name: borde_mitm_converter
    volumes:
      - ./mitm/data:/data
      - ./mitm/capture.py:/app/capture.py
    networks:
      - borde_net
    command: python3 /app/capture.py
    depends_on:
      - mitm

networks:
  borde_net:
    driver: bridge
